### ISSUE TITLE
:openssl_verify_mode=>"peer" can cause OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by becomingwisest** [mikel/mail#1076]
If i set :openssl_verify_mode=>"peer" as part of Mail.defaults do delivery_method :smtp, would fail to send emails in the two environments I have access too unless I pass in a certificate file to verify the cert from.

I've got code that throws a RuntimeError if OpenSSL::SSL::VERIFY_PEER is being set, but there isn't ca_file or ca_path being passed in, or being provided by default.

I'm working on the test(s), and updated documentation and examples.

--

In Ubuntu 12.04, running 1.9.3 from https://www.brightbox.com/docs/ruby/ubuntu/
```
irb(main):015:0> Net::SMTP.default_ssl_context.ca_path
=> nil
irb(main):016:0> Net::SMTP.default_ssl_context.ca_file
=> nil
irb(main):017:0> RUBY_VERSION
=> "1.9.3"
```

With OSX 10.11.6, with rvm running MRI ruby 2.2.3, and openssl installed via homebrew.
```
Loading development environment (Rails 4.2.4)
[1] pry(main)> Mail.defaults do
[1] pry(main)*   delivery_method :smtp, {
[1] pry(main)*     address: 'smtp.sendgrid.net',
[1] pry(main)*     port: 587,
[1] pry(main)*     domain: ENV.fetch('SMTP_DOMAIN'),
[1] pry(main)*     user_name: ENV.fetch('SMTP_USERNAME'),
[1] pry(main)*     password: ENV.fetch('SMTP_PASSWORD'),
[1] pry(main)*     authentication: 'plain',
[1] pry(main)*     enable_starttls_auto: true,
[1] pry(main)*     openssl_verify_mode: 'peer'
[1] pry(main)*   }
[1] pry(main)*
[1] pry(main)* end
=> #<Mail::SMTP:0x007fa43602b598
 @settings=
  {:address=>"smtp.sendgrid.net",
   :port=>587,
   :domain=>"...",
   :user_name=>"...",
   :password=>"...",
   :authentication=>"plain",
   :enable_starttls_auto=>true,
   :openssl_verify_mode=>"peer",
   :ssl=>nil,
   :tls=>nil}>
[2] pry(main)> Mail.deliver do
[2] pry(main)*   from     'becomingwisest@gmail.com'
[2] pry(main)*   to       'becomingwisest@gmail.com'
[2] pry(main)*   subject  'testing sendgrid'
[2] pry(main)*   body     'testing sendgrid'
[2] pry(main)* end
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
from /Users/christopher.evans/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/smtp.rb:586:in `connect'
[3] pry(main)> Net::SMTP.default_ssl_context.ca_path
=> nil
[4] pry(main)> Net::SMTP.default_ssl_context.ca_file
=> nil
[5] pry(main)> RUBY_VERSION
=> "2.2.3"
```

If I specify '/usr/local/etc/openssl/cert.pem' as the ca_file, it works.
```
Loading development environment (Rails 4.2.4)
[1] pry(main)> Mail.defaults do
[1] pry(main)*   delivery_method :smtp, {
[1] pry(main)*     address: 'smtp.sendgrid.net',
[1] pry(main)*     port: 587,
[1] pry(main)*     domain: ENV.fetch('SMTP_DOMAIN'),
[1] pry(main)*     user_name: ENV.fetch('SMTP_USERNAME'),
[1] pry(main)*     password: ENV.fetch('SMTP_PASSWORD'),
[1] pry(main)*     authentication: 'plain',
[1] pry(main)*     enable_starttls_auto: true,
[1] pry(main)*     openssl_verify_mode: 'peer',
[1] pry(main)*     ca_file: '/usr/local/etc/openssl/cert.pem'
[1] pry(main)*   }
[1] pry(main)*
[1] pry(main)* end
=> #<Mail::SMTP:0x007f90a1e450a0
 @settings=
  {:address=>"smtp.sendgrid.net",
   :port=>587,
   :domain=>"...",
   :user_name=>"...",
   :password=>"...",
   :authentication=>"plain",
   :enable_starttls_auto=>true,
   :openssl_verify_mode=>"peer",
   :ssl=>nil,
   :tls=>nil,
   :ca_file=>"/usr/local/etc/openssl/cert.pem"}>
[2] pry(main)> Mail.deliver do
[2] pry(main)*   from     'becomingwisest@gmail.com'
[2] pry(main)*   to       'becomingwisest@gmail.com'
[2] pry(main)*   subject  'testing sendgrid'
[2] pry(main)*   body     'testing sendgrid'
[2] pry(main)* end
=> #<Mail::Message:70129600622660, Multipart: false, Headers: <Date: Fri, 27 Jan 2017 11:07:02 -0800>, <From: becomingwisest@gmail.com>, <To: becomingwisest@gmail.com>, <Message-ID: <588b9a5673050_12f93fc850c5e204548ba@ChristopherEvans.local.mail>>, <Subject: testing sendgrid>, <Mime-Version: 1.0>, <Content-Type: text/plain>, <Content-Transfer-Encoding: 7bit>>

**Comment by jeremy** [comment]
This is a known trouble spot with Ruby + OpenSSL on macOS.

For RVM, check this out: https://rvm.io/support/fixing-broken-ssl-certificates

```bash
rvm osx-ssl-certs update all
```

**Comment by becomingwisest** [comment]
Is this also a known issue with rvm and ubuntu, because where it failed in our qa environment.

I also did some testing with the Docker ruby image based on alpine linux.

https://gist.github.com/becomingwisest/983d2e71770df889579d1b6544fc6f19

Is there a known/supported platform that allows openssl_verify_mode: 'peer' but doesn't require ca_file, or ca_path to be set?

**Comment by jeremy** [comment]
> Is there a known/supported platform that allows openssl_verify_mode: 'peer' but doesn't require ca_file, or ca_path to be set?

That's up to your OpenSSL config. If the default CA path (or file) includes current root certificates, it'll always work out of the box. This is true for most distributions.

If the certs are outdated, you'll need to update them. Use your distro's tooling to update your CA certs. On Ubuntu, that's `update-ca-certificates`: http://manpages.ubuntu.com/manpages/trusty/man8/update-ca-certificates.8.html

On an Alpine container, you need to install ca-certificates first in your Dockerfile, e.g. `apk --no-cache add ca-certificates && update-ca-certificates`

In any case! This is far out of scope for the Ruby Mail library 😊

**Comment by nanaya** [comment]
It doesn't seem to use openssl default though.

This doesn't work:

```ruby
require 'mail'

Mail.defaults do
  delivery_method :smtp, {
    address: 'smtp.fastmail.com',
    port: 465,
    user_name: '<REDACTED>',
    password: '<REDACTED>',
    authentication: 'plain',
    tls: true,
    openssl_verify_mode: 'peer'
  }

end
Mail.deliver do
  from     '<REDACTED>'
  to       '<REDACTED>'
  subject  'testing fastmail'
  body     'testing fastmail'
end

# raises /opt/ruby24/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
```

But this does:

```ruby
require 'net/https'
require 'uri'

url = URI.parse "https://myconan.net/"
# to make sure it's actually VERIFY_PEER, uncomment the following line to raise exception instead.
#url = URI.parse "https://160.16.83.235/"

http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_PEER
request = Net::HTTP::Get.new(url.path)
response = http.request(request)

puts response.code # 200
```
```

**Comment by nanaya** [comment]
According to [this](https://gitlab.com/gitlab-org/gitlab-ce/issues/1558#note_1185132), `set_params` must be called for `ca_*` parameters to be filled in with defaults.
