### ISSUE TITLE
Finding emails from specific email addresses

### ISSUE THREAD

**Issue by isaacjoy** [mikel/mail#1132]
Is it possible to find emails from an array of email addresses? I've seen the thread for getting unread messages like so:

**new_messages = Mail.find(keys: ['NOT','SEEN'])**

But I cannot find how to get messages from a certain address. I've tried:

**new_messages = Mail.find(keys: ['FROM','example@hello.com'])**,

but it's not working.

I know [section 6.4.4 of the IMAP protocol](https://tools.ietf.org/html/rfc3501) indicates the different search flags you can use to search for messages, but I can't seem to get the right syntax.

Thanks for creating a really awesome gem

**Comment by jeremy** [comment]
Hey @isaacjoy, you're doing it right. When you've configured an IMAP retriever_method, then `Mail.find` [passes :keys through to IMAP#uid_search](https://github.com/mikel/mail/blob/master/lib/mail/network/retriever_methods/imap.rb#L78) directly, which takes the [same args as IMAP#search](http://ruby-doc.org/stdlib-2.4.1/libdoc/net/imap/rdoc/Net/IMAP.html#method-i-search).

**Comment by Nakilon** [comment]
How do I search by non-ascii subject?
The exception happens in the stdlib `net/imap.rb`:
```ruby
    def send_string_data(str, tag = nil)
p str
      case str
      when ""
        put_string('""')
      when /[\x80-\xff\r\n]/n
        # literal
        send_literal(str, tag)
      when /[(){ \x00-\x1f\x7f%*"\\]/n
        # quoted string
        send_quoted_string(str)
      else
        put_string(str)
      end
    end
```
```none
FROM "subscribe@..."
subscribe@... "SUBJECT"
SUBJECT "\"Новый заказ *\""
Traceback (most recent call last):
	17: from main.rb:3:in `<main>'
	16: from /Users/nakilon/_/REPOS/simple_gmail/lib/simple_gmail.rb:57:in `read_imap'
	15: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/mail.rb:140:in `find'
	14: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/imap.rb:76:in `find'
	13: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/imap.rb:179:in `start'
	12: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/imap.rb:78:in `block in find'
	11: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:779:in `uid_search'
	10: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:1417:in `search_internal'
	 9: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	 8: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:1421:in `block in search_internal'
	 7: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:1255:in `send_command'
	 6: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	 5: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:1261:in `block in send_command'
	 4: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:1261:in `each'
	 3: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:1263:in `block (2 levels) in send_command'
	 2: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:1328:in `send_data'
	 1: from /Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:1347:in `send_string_data'
/Users/nakilon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/imap.rb:1347:in `===': incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string) (Encoding::CompatibilityError)
```
