### ISSUE TITLE
Problem with using instance variable for email address

### ISSUE THREAD

**Issue by michaelxwang** [mikel/mail#1150]
Here is the test code:

```
$ cat mail4.rb

require 'mail'

class Mailx
   def initialize(to)
      @to = to
   end

   def send
      to = @to
      Mail.deliver do
         to      @to   # It works if I use to instead of @to
         from    "xxxx@columbia.edu"
         subject "Your MySQL account"

         html_part do
            content_type 'text/html; charset=UTF-8'
            body '<h1>This is HTML</h1>'
         end
      end
   end
end

mailx = Mailx.new("john_smith@3com.com")
mailx.send()

```

Here is the running result:

```
$ ruby mail4.rb

/Library/Ruby/Gems/2.0.0/gems/mail-2.6.6/lib/mail/check_delivery_params.rb:21:in `check_to': SMTP To address may not be blank: [] (ArgumentError)
        from /Library/Ruby/Gems/2.0.0/gems/mail-2.6.6/lib/mail/check_delivery_params.rb:7:in `check'
        from /Library/Ruby/Gems/2.0.0/gems/mail-2.6.6/lib/mail/network/delivery_methods/smtp.rb:97:in `deliver!'
        from /Library/Ruby/Gems/2.0.0/gems/mail-2.6.6/lib/mail/message.rb:2149:in `do_delivery'
        from /Library/Ruby/Gems/2.0.0/gems/mail-2.6.6/lib/mail/message.rb:239:in `deliver'
        from /Library/Ruby/Gems/2.0.0/gems/mail-2.6.6/lib/mail/mail.rb:141:in `deliver'
        from mail4.rb:10:in `send'
        from mail4.rb:24:in `<main>'
```

Comment: I believe that somehow the at sign "@" instance variable @to interferes with the Mail module. If I assign instance variable @to with at sign "@" to a local variable "to" without at sign "@", and then use the local variable to, then it works.

**Comment by jeremy** [comment]
`Mail.deliver do …` passes a block to `Mail.new` which calls `instance_eval` on it, so it can't "see" your `@to` variable.

Use the hash interface instead to work around this:
```ruby
Mail.new(to: @to, …).deliver
```
