### ISSUE TITLE
CRLF problems in 2.7.0

### ISSUE THREAD

**Issue by kstefanini** [mikel/mail#1174]
Hello :)
Since mail 2.7.0 got this this error using Mailcatcher:

```
/usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:31:in `block in check_addr': SMTP To address may not contain CR or LF line breaks: "sender@local.dev\nSubject: [Projet] Mot de passe r\u00E9initialis\u00E9\nX-PHP-Originating-Script: 33:class-phpmailer.php\nDate: Wed, 22 Nov 2017 17:31:58 +0000\nFrom: WordPress <wordpress@local.dev>\nMessage-ID: <56e034b5d1ee66aeaa48c1546ade0afd@local.dev>\nX-Mailer: PHPMailer 5.2.22 (https://github.com/PHPMailer/PHPMailer)\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n\nQuelqu\u2019un a demand\u00E9 la r\u00E9initialisation du mot de passe pour le compte suivant\u00A0:\n\nhttp://local.dev:8090/\n\nIdentifiant : local\n\nS\u2019il s\u2019agit d\u2019une erreur, ignorez ce message et la demande ne sera pas prise en compte.\n\nPour renouveler votre mot de passe, cliquez sur le lien suivant\u00A0:\n\n<http://local.dev:8090/wp-login.php?action=rp&key=YElneAztfaLlNs8OSWq1&login=local>" (ArgumentError)
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:42:in `validate_smtp_addr'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:30:in `check_addr'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:25:in `block in check_to'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:24:in `map'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:24:in `check_to'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:7:in `check'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp_connection.rb:52:in `deliver!'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:101:in `block in deliver!'
  from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/smtp.rb:519:in `start'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/message.rb:2160:in `do_delivery'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mail-2.7.0/lib/mail/message.rb:262:in `deliver'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/gems/mailcatcher-0.6.5/bin/catchmail:71:in `<top (required)>'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/bin/catchmail:23:in `load'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/bin/catchmail:23:in `<main>'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/bin/ruby_executable_hooks:15:in `eval'
  from /usr/local/rvm/gems/ruby-2.4.1@mailcatcher/bin/ruby_executable_hooks:15:in `<main>'
```

And i have no error with mail 2.6.6.

**Comment by jeremy** [comment]
See #1167 and #1168
