### ISSUE TITLE
read_from_string 7bit messages

### ISSUE THREAD

**Issue by JerryGreen** [mikel/mail#1202]
Looks like read_from_string cannot read email messages with:
```
Content-Transfer-Encoding: 7bit
```

I found one of these in my 8k email box (and it's the only one). All of them handled good but on this one the lib just crashes.

All I do is just:
```
mail = Mail.read_from_string(imap.uid_fetch(uid, 'RFC822')[0].attr['RFC822'])
puts mail
```

It crashes when I try to call any method on `mail` or even if I just output it

Stack trace:
```
rails aborted!
Encoding::CompatibilityError: incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/utilities.rb:42:in `==='
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/utilities.rb:42:in `token_safe?'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/utilities.rb:48:in `quote_token'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/fields/common/parameter_hash.rb:55:in `block in decoded'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/fields/common/parameter_hash.rb:54:in `map!'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/fields/common/parameter_hash.rb:54:in `decoded'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/fields/content_disposition_field.rb:63:in `decoded'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/fields/structured_field.rb:44:in `default'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/field.rb:237:in `method_missing'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:1215:in `default'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:581:in `content_disposition'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:2144:in `find_attachment'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:1931:in `attachment?'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/parts_list.rb:67:in `get_order_value'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/parts_list.rb:58:in `block in sort!'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/parts_list.rb:54:in `each'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/parts_list.rb:54:in `sort_by'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/parts_list.rb:54:in `sort!'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/body.rb:133:in `sort_parts!'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/body.rb:152:in `encoded'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:1833:in `encoded'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:1896:in `to_s'
/Users/jerrygreen/projects/my_project/backend/app/lib/mail_saver.rb:9:in `puts'
/Users/jerrygreen/projects/my_project/backend/app/lib/mail_saver.rb:9:in `puts'
/Users/jerrygreen/projects/my_project/backend/app/lib/mail_saver.rb:9:in `save_mail'
/Users/jerrygreen/projects/my_project/backend/lib/tasks/imap.rake:122:in `block (3 levels) in <top (required)>'
/Users/jerrygreen/projects/my_project/backend/lib/tasks/imap.rake:89:in `reverse_each'
/Users/jerrygreen/projects/my_project/backend/lib/tasks/imap.rake:89:in `with_index'
/Users/jerrygreen/projects/my_project/backend/lib/tasks/imap.rake:89:in `block (2 levels) in <top (required)>'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:6:in `require'
bin/rails:6:in `<main>'
```

**Comment by JerryGreen** [comment]
A bit of strange things: When I see `mail.parts.count`, it's just 2. But when I map these parts and try to output some info, there's THREE steps in that cycle. If I try to see `part.content_type`:

1
multipart/alternative; boundary="=_f79b375f1558c9087d97a6ea7ca69302"
2
text/x-vcard; charset=utf-8; profile=vcard
3
multipart/mixed; boundary="=_5e1041d00b6105490ffaa6127b6f1622"

If I try to output full string of the part, I see them for 1 and 2 (so I don't see any sense to post it here), but on the last one I get the same error!

So there's some problems with `to_s` for `Mail::Message` when it's `multipart/mixed`

**Comment by JerryGreen** [comment]
Another interesting stacktrace, probably related to this issue too:

```
Encoding::UndefinedConversionError: "\xD0" from ASCII-8BIT to UTF-8
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/core_ext/object/json.rb:34:in `encode'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/core_ext/object/json.rb:34:in `to_json'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/core_ext/object/json.rb:34:in `to_json'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/json/encoding.rb:55:in `to_json'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/json-2.1.0/lib/json/common.rb:224:in `generate'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/json-2.1.0/lib/json/common.rb:224:in `generate'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/json/encoding.rb:99:in `stringify'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/json/encoding.rb:33:in `encode'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/json/encoding.rb:20:in `encode'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/type/internal/abstract_json.rb:23:in `serialize'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activemodel-5.0.6/lib/active_model/type/helpers/mutable.rb:6:in `cast'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute.rb:150:in `type_cast'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute.rb:38:in `value'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute.rb:123:in `changed_from_assignment?'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute.rb:55:in `changed?'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute_mutation_tracker.rb:25:in `changed?'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute_mutation_tracker.rb:9:in `block in changed_values'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute_mutation_tracker.rb:8:in `each'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute_mutation_tracker.rb:8:in `each_with_object'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute_mutation_tracker.rb:8:in `changed_values'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute_methods/dirty.rb:83:in `changed_attributes'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activemodel-5.0.6/lib/active_model/dirty.rb:146:in `changed'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute_methods/dirty.rb:127:in `keys_for_partial_write'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute_methods/dirty.rb:123:in `_create_record'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/callbacks.rb:302:in `block in _create_record'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:126:in `call'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/callbacks.rb:302:in `_create_record'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/timestamp.rb:68:in `_create_record'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/persistence.rb:548:in `create_or_update'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/callbacks.rb:298:in `block in create_or_update'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:126:in `call'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:455:in `call'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/callbacks.rb:298:in `create_or_update'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/persistence.rb:129:in `save'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/validations.rb:44:in `save'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/attribute_methods/dirty.rb:22:in `save'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/transactions.rb:319:in `block (2 levels) in save'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/transactions.rb:211:in `transaction'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/transactions.rb:319:in `block in save'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/transactions.rb:318:in `save'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/suppressor.rb:41:in `save'
/Users/jerrygreen/projects/my_project/backend/app/lib/mail_to_entity_translator.rb:29:in `block in save'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/transactions.rb:211:in `transaction'
/Users/jerrygreen/projects/my_project/backend/app/lib/mail_to_entity_translator.rb:27:in `save'
/Users/jerrygreen/projects/my_project/backend/lib/tasks/imap.rake:125:in `block (3 levels) in <top (required)>'
/Users/jerrygreen/projects/my_project/backend/lib/tasks/imap.rake:84:in `reverse_each'
/Users/jerrygreen/projects/my_project/backend/lib/tasks/imap.rake:84:in `with_index'
/Users/jerrygreen/projects/my_project/backend/lib/tasks/imap.rake:84:in `block (2 levels) in <top (required)>'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:6:in `require'
bin/rails:6:in `<main>'
```

That's when I try to save `mail.html_part&.body&.to_s` to DB (jsonb field)

Not sure, but maybe it's related to errors with Rails5 (I'm using 5.0.2)

**Comment by JerryGreen** [comment]
Looks like a problem with cyrillic characters, look at this

```
2.4.1 :001 > "\xD0".encode('UTF-8', 'ASCII-8BIT')
Encoding::UndefinedConversionError: "\xD0" from ASCII-8BIT to UTF-8
	from (irb):88:in `encode'
	from (irb):88
	from /Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
	from /Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/jerrygreen/.rvm/gems/ruby-2.4.1/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:6:in `require'
	from bin/rails:6:in `<main>'
```

That's what is happening here

**Comment by jeremy** [comment]
Looks like an invalid filename in the Content-Disposition header.

Could you narrow this down to a simple, reproducible case?

**Comment by ahorek** [comment]
also some headers that were just ignored in 2.6 are parsed now, but as ASCII-8bit. Trying to convert them to utf-8 could raise invalid conversion errors. I'm not sure whether this behaviour is correct or not.

for the first bug, I've already submitted a PR https://github.com/mikel/mail/pull/1191

**Comment by JerryGreen** [comment]
@ahorek I'm using `mail` 2.7.0. You think if I use 2.6, there will not be such a bug? And yea, you correctly noticed - here's actually two different bugs. However, they both are related to encodings, `ASCII-8BIT` and `UTF-8`. Just maybe they both can be fixed with a single mechanism.

[The second bug](https://github.com/mikel/mail/issues/1202#issuecomment-366442440), I suppose, I can bypass this by playing with `force_encoding`. Found [this answer](https://stackoverflow.com/a/15818886/3720305) ("Encoding Issues" & "Hard Encoding Issues" parts). Looks like a solution. I'll make sure it works later.

For the first ([original](https://github.com/mikel/mail/issues/1202#issue-297990721)) bug... Maybe I can save that strange email to file and attach here, so it'll be possible to reproduce this strange bug... Idk. Let's see.

I'll keep you posted here.
