### ISSUE TITLE
undefined method 'can_transport?' for nil:NilClass

### ISSUE THREAD

**Issue by Yaroslav-F** [mikel/mail#1207]
Can't quite dig down to the possible cause of this error. Backtrace:
```
…ems/mail-2.7.0/lib/mail/encodings/transfer_encoding.rb:  49:in `block in renegotiate'
…ems/mail-2.7.0/lib/mail/encodings/transfer_encoding.rb:  47:in `select'
…ems/mail-2.7.0/lib/mail/encodings/transfer_encoding.rb:  47:in `renegotiate'
…ems/mail-2.7.0/lib/mail/encodings/transfer_encoding.rb:  42:in `negotiate'
…dor/bundle/ruby/2.5.0/gems/mail-2.7.0/lib/mail/body.rb: 143:in `negotiate_best_encoding'
…dor/bundle/ruby/2.5.0/gems/mail-2.7.0/lib/mail/body.rb: 157:in `encoded'
…/bundle/ruby/2.5.0/gems/mail-2.7.0/lib/mail/message.rb:1833:in `encoded'
…dor/bundle/ruby/2.5.0/gems/mail-2.7.0/lib/mail/body.rb: 153:in `block in encoded'
…ndle/ruby/2.5.0/gems/mail-2.7.0/lib/mail/parts_list.rb:  31:in `block in collect'
…2user/.rbenv/versions/2.5.0/lib/ruby/2.5.0/delegate.rb: 349:in `each'
…2user/.rbenv/versions/2.5.0/lib/ruby/2.5.0/delegate.rb: 349:in `block in delegating_block'
…ndle/ruby/2.5.0/gems/mail-2.7.0/lib/mail/parts_list.rb:  31:in `collect'
…dor/bundle/ruby/2.5.0/gems/mail-2.7.0/lib/mail/body.rb: 153:in `encoded'
…/bundle/ruby/2.5.0/gems/mail-2.7.0/lib/mail/message.rb:1833:in `encoded'
…/bundle/ruby/2.5.0/gems/mail-2.7.0/lib/mail/message.rb: 260:in `deliver'
…/sidekiq-5.1.1/lib/sidekiq/extensions/action_mailer.rb:  33:in `deliver'
```
Can message_encoding be nil?

Body of the email looks pretty standard. It has 4 attachments though:
2 pdf docs, 1 txt doc and 1 eml file which is an email with inline image inside.

UPD:
Happens for all emails with .eml attachments.

UPD2:
might be related to https://github.com/mikel/mail/issues/1022

**Comment by ahorek** [comment]
fixed by https://github.com/mikel/mail/pull/1176
