### ISSUE TITLE
Installing Gem when 'yard config --gem-install-yri' is set raises a SystemStackError

### ISSUE THREAD

**Issue by jdickey** [mikel/mail#1211]
Gem version 2.7.0 as installed from rubygems.org
Ruby version 2.5.0 on Debian Jessie. Replicated on OS X 10.11.6, also with MRI Ruby 2.5.0

## Observed behaviour

```
$ gem install mail -v 2.7.0
Fetching: mail-2.7.0.gem (100%)
Successfully installed mail-2.7.0
Building YARD (yri) index for mail-2.7.0...
/usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ast_node.rb:212:in `block in traverse': stack level too deep (SystemStackError)
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ast_node.rb:210:in `each'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ast_node.rb:210:in `with_index'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ast_node.rb:210:in `traverse'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ruby_parser.rb:601:in `insert_comments'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ruby_parser.rb:60:in `parse'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:442:in `parse'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:46:in `block in parse'
	 ... 30 levels...
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/command_manager.rb:171:in `process_args'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/command_manager.rb:141:in `run'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/gem_runner.rb:59:in `run'
	from /usr/local/bin/gem:21:in `<main>'
$
```

## Expected behaviour

```
gem install mail -v 2.7.0
Fetching: mail-2.7.0.gem (100%)
Successfully installed mail-2.7.0
Building YARD (yri) index for mail-2.7.0...
Done installing documentation for mail after 0 seconds
1 gem installed
$
```

**Comment by jeremy** [comment]
Hey @jdickey, this is a YARD issue. Check out e.g. https://github.com/lsegal/yard/issues/1002
