### ISSUE TITLE
nil::class error in /mail-2.7.0/lib/mail/encodings/transfer_encoding.rb:49:in `block in renegotiate'

### ISSUE THREAD

**Issue by kathyygao** [mikel/mail#1236]
When running mail gem 2.7.0, we encounter the following nil::class error:
 NoMethodError:
       undefined method `can_transport?' for nil:NilClass
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/encodings/transfer_encoding.rb:49:in `block in renegotiate'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/encodings/transfer_encoding.rb:47:in `select'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/encodings/transfer_encoding.rb:47:in `renegotiate'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/encodings/transfer_encoding.rb:42:in `negotiate'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/body.rb:143:in `negotiate_best_encoding'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/body.rb:157:in `encoded'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/message.rb:1833:in `encoded'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/body.rb:153:in `block in encoded'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/parts_list.rb:31:in `block in collect'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/parts_list.rb:31:in `collect'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/body.rb:153:in `encoded'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.7.0/lib/mail/message.rb:1833:in `encoded'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/actionmailer-4.2.9/lib/action_mailer/base.rb:562:in `set_payload_for_mail'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/actionmailer-4.2.9/lib/action_mailer/base.rb:542:in `block in deliver_mail'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `block in instrument'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `instrument'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/actionmailer-4.2.9/lib/action_mailer/base.rb:541:in `deliver_mail'

the root cause is the latest mail gem (2.7.0), it does not have nil check under mail/encodings/transfer_encoding.rb:49
source code for transfer_encoding.rb

def self.renegotiate(message_encoding, source_encoding, str, allowed_encodings = nil)
encodings = Encodings.get_all.select do |enc|
(allowed_encodings.nil? || allowed_encodings.include?(enc)) &&
message_encoding.can_transport?(enc) &&
enc.can_encode?(source_encoding)
end

lowest_cost(str, encodings)
end

message_encoding could be nil, but it is not nil-checked..

**Comment by jeremy** [comment]
Appears to be #1176. Could you check against 2.7.1.rc1 gem or the master branch?
