### ISSUE TITLE
incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by khiav223577** [mikel/mail#1356]
I got this error when my email subject contains multi-byte characters.

```
Failure/Error: expect(mailer.last).to have_mail_html_link("https://example.com/ConfirmEmail?user_id=#{User.
last.id}&confirm_email_token=")

     Encoding::CompatibilityError:
       incompatible character encodings: ASCII-8BIT and UTF-8
     # /home/khiav/.rvm/gems/ruby-2.5.5/gems/mail-2.7.1/lib/mail/header.rb:227:in `join'
     # /home/khiav/.rvm/gems/ruby-2.5.5/gems/mail-2.7.1/lib/mail/header.rb:227:in `field_summary'
     # /home/khiav/.rvm/gems/ruby-2.5.5/gems/mail-2.7.1/lib/mail/message.rb:1900:in `inspect'
     # ./spec/requests/users_spec.rb:24:in `block (3 levels) in <top (required)>'
```

I think the bug is caused by `Socket.gethostname`
https://github.com/mikel/mail/blob/6b0ebb142c476bf7c00524effe513a4f151f59ab/lib/mail/utilities.rb#L326

The return value's encoding of `Socket.gethostname` in my computer is ASCII-8BIT
```rb
Socket.gethostname
# => "\xE6\x9C\x88\xE6\x9C\x88\xE7\x9A\x84\xE7\xAD\x86\xE9\x9B\xBB"

Socket.gethostname.encoding
# => #<Encoding:ASCII-8BIT>

['狼', Socket.gethostname].join
# Traceback (most recent call last):
#         2: from (irb):10
#         1: from (irb):10:in `join'
# Encoding::CompatibilityError (incompatible character encodings: UTF-8 and ASCII-8BIT)
```

I have no idea how to fix it :(

**Comment by jeremy** [comment]
Also see #1073 and #555
