### ISSUE TITLE
rc3 Issue with delayed_job

### ISSUE THREAD

**Issue by mzagaja** [mikel/mail#1509]
When using a rails app we include [per this advice](https://github.com/mikel/mail/pull/1472#issuecomment-1197111589):

```
gem "mail", ">= 2.8.0.rc1" # See https://github.com/mikel/mail/pull/1472#issuecomment-1197111589
```

in the Gemfile. Then get the following from `bin/delayed_job start`in our log file:

```
/var/www/donkey/staging/bump-gems-ruby-31-fbranch/shared/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- mail/indifferent_hash (LoadError)
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/shared/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/shared/bundle/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/shared/bundle/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/shared/bundle/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/shared/bundle/ruby/3.1.0/gems/mail-2.8.0.rc3/lib/mail.rb:14:in `<module:Mail>'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/shared/bundle/ruby/3.1.0/gems/mail-2.8.0.rc3/lib/mail.rb:3:in `<top (required)>'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/shared/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/shared/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/runtime.rb:55:in `each'
	from /usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
	from /usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/runtime.rb:44:in `each'
	from /usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler/runtime.rb:44:in `require'
	from /usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/bundler.rb:186:in `require'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/releases/20221130200132/config/application.rb:28:in `<top (required)>'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/releases/20221130200132/config/environment.rb:2:in `require_relative'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/releases/20221130200132/config/environment.rb:2:in `<top (required)>'
	from <internal:/usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/www/donkey/staging/bump-gems-ruby-31-fbranch/releases/20221130200132/bin/delayed_job:3:in `<main>'
```

We have currently mitigated by downgrading back to version 2.7.0 and then adding:

```ruby
gem "net-imap", require: false
gem "net-pop", require: false
gem "net-smtp", require: false # See https://github.com/mikel/mail/pull/1472#issuecomment-1197111589
```
to our Gemfile.

**Comment by mzagaja** [comment]
I think this might actually be a deployment issue for us involving RVM, so I'm closing this.
