### ISSUE TITLE
certificate verify failed (unable to get local issuer certificate) 

### ISSUE THREAD

**Issue by HarshRajIN** [mikel/mail#1537]
Running into SSL issue while sending SMTP mail on version 2.8.0, while it works all fine with 2.7.1.
```
**SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)** 
	/usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in 'connect_nonblock'
	/usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in 'ssl_socket_connect'
	/usr/local/bundle/gems/net-smtp-0.3.3/lib/net/smtp.rb:690:in 'tlsconnect'
	/usr/local/bundle/gems/net-smtp-0.3.3/lib/net/smtp.rb:666:in 'do_start'
	/usr/local/bundle/gems/net-smtp-0.3.3/lib/net/smtp.rb:611:in 'start'
	/usr/local/bundle/gems/mail-2.8.0/lib/mail/network/delivery_methods/smtp.rb:109:in 'start_smtp_session'
	/usr/local/bundle/gems/mail-2.8.0/lib/mail/network/delivery_methods/smtp.rb:100:in 'deliver!'
	/usr/local/bundle/gems/mail-2.8.0/lib/mail/message.rb:269:in 'deliver!'
```

**Comment by HarshRajIN** [comment]
`Ruby 2.6.4`

**Comment by eval** [comment]
@HarshRajIN what config did you use?

**Comment by HarshRajIN** [comment]
```
def self.send_using_options(options, environment)
        options[:from] = 'no_reply@company.com'
        options[:via] = :smtp
        options[:via_options] = {
          address: smtp_server_address(environment),
          port: '25',
          domain: 'company.com'
        }
        Pony.mail(options)
      end
```
Log-
```
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) 
	/usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
	/usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
	/usr/local/bundle/gems/net-smtp-0.3.3/lib/net/smtp.rb:690:in `tlsconnect'
	/usr/local/bundle/gems/net-smtp-0.3.3/lib/net/smtp.rb:666:in `do_start'
	/usr/local/bundle/gems/net-smtp-0.3.3/lib/net/smtp.rb:611:in `start'
	/usr/local/bundle/gems/mail-2.8.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
	/usr/local/bundle/gems/mail-2.8.0/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
	/usr/local/bundle/gems/mail-2.8.0/lib/mail/message.rb:269:in `deliver!'
	/usr/local/bundle/gems/pony-1.13.1/lib/pony.rb:177:in `deliver'
	/usr/local/bundle/gems/pony-1.13.1/lib/pony.rb:166:in `mail'
	/usr/local/bundle/gems/cert-app-2.4.0/lib/cert_app/util/mail.rb:33:in `send_using_options'
```

**Comment by eval** [comment]
Newer versions of `net-smtp` will do starttls by default.

From mail v2.8 you can override this. Try
```diff
def self.send_using_options(options, environment)
        options[:from] = 'no_reply@company.com'
        options[:via] = :smtp
        options[:via_options] = {
          address: smtp_server_address(environment),
          port: '25',
<         domain: 'company.com'
>         domain: 'company.com',
>         enable_starttls: false
        }
        Pony.mail(options)
      end
```
