### ISSUE TITLE
invalid date throws error

### ISSUE THREAD

**Issue by dgm** [mikel/mail#216]
When processing a message that has an invalid date, I had a rails page crash.  Does Mail do this for all parsing errors, or can it catch the errors and return the best parse it can?  The nature of my project (Maia Mailguard) is such that I am sure to have broken messages that I'm trying to look at.  If you want edge cases to test against, I'm sure I can find them :)

invalid date

```
/Users/dgm/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/date.rb:1688:in `new_by_frags'
/Users/dgm/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/date.rb:1733:in`parse'
mail (2.2.9) lib/mail/fields/date_field.rb:41:in `initialize'
mail (2.2.9) lib/mail/field.rb:176:in`new'
mail (2.2.9) lib/mail/field.rb:176:in `new_field'
mail (2.2.9) lib/mail/field.rb:145:in`create_field'
mail (2.2.9) lib/mail/field.rb:74:in `initialize'
mail (2.2.9) lib/mail/header.rb:78:in`new'
mail (2.2.9) lib/mail/header.rb:78:in `block in fields='
mail (2.2.9) lib/mail/header.rb:76:in`each'
mail (2.2.9) lib/mail/header.rb:76:in `fields='
mail (2.2.9) lib/mail/header.rb:252:in`split_header'
mail (2.2.9) lib/mail/header.rb:40:in `initialize'
mail (2.2.9) lib/mail/message.rb:364:in`new'
mail (2.2.9) lib/mail/message.rb:364:in `header='
mail (2.2.9) lib/mail/message.rb:1774:in`parse_message'
mail (2.2.9) lib/mail/message.rb:1903:in `init_with_string'
mail (2.2.9) lib/mail/message.rb:124:in`initialize'
mail (2.2.9) lib/mail/mail.rb:50:in `new'
mail (2.2.9) lib/mail/mail.rb:50:in`new'
mail (2.2.9) lib/mail/mail.rb:187:in `read_from_string'
```

**Comment by jeremy** [comment]
#593
