### ISSUE TITLE
Address fails to parse email addresses with extended characters

### ISSUE THREAD

**Issue by kevn** [mikel/mail#39]
For example, "josé.cuervo@cactus.com"

```
AddressListsParser can not parse |josé.cuervo@cactus.com|
Reason was: Expected one of !, #, $, %, &, ', *, +, -, /, =, ?, ^, _, `, {, |, }, ~, 
, (, ", ., :, <, @, , at line 1, column 4 (byte 4) after 
/opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/mail-2.1.3/lib/mail/elements/address_list.rb:29:in `initialize'
```

Judging by our data, these are becoming quite common.

**Comment by lunaru** [comment]
Which version of mail will include this fix? I see that it's not in the latest 2.6 release yet. Is this something slated for 2.7.x?

**Comment by jeremy** [comment]
@lunaru 2.7.0! You can try with 2.7.0.rc1 or bundle against the master branch.

**Comment by beders** [comment]
Thanks for working on this. It is greatly appreciated.
I tested with 2.7.0.rc1 but it doesn't seem to be happy with umlauts:
Here's an example:

```
>> puts Gem.loaded_specs["mail"].version
2.7.0.rc1
nil
>> Mail::Address.new('über <uber@mail.com>')
Mail::Field::ParseError: Mail::AddressList can not parse |über <uber@mail.com>|
Reason was: Only able to parse up to ü
	from /Users/beders/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mail-2.7.0.rc1/lib/mail/parsers/address_lists_parser.rb:15336:in `parse'
	from /Users/beders/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mail-2.7.0.rc1/lib/mail/elements/address.rb:191:in `parse'
	from /Users/beders/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mail-2.7.0.rc1/lib/mail/elements/address.rb:31:in `initialize'
	from (irb):9:in `new'
	from (irb):9
```

**Comment by lunaru** [comment]
@beders I had the same problem. It looks like it's not in the 2.7.0.rc1 branch, but rather only on master still

**Comment by beders** [comment]
@lunaru Thank you! That indeed works!

**Comment by Erowlin** [comment]
Bump, any fixes scheduled to head on the master branch? Thanks.
