### ISSUE TITLE
Encoding windows-1258 in subject breaks in conversion to UTF-8

### ISSUE THREAD

**Issue by gauteh** [mikel/mail#544]
A thread-topic, or subject with the title: `<Subject: =?windows-1258?Q?SV=3A_Spr=F8sm=E5l_om_tilbod?=>`

fails with:

```
1.9.3-p392 :004 > m.subject
Encoding::ConverterNotFoundError: code converter not found (Windows-1258 to UTF-8)
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/version_specific/ruby_1_9.rb:77:in `encode'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/version_specific/ruby_1_9.rb:77:in `q_value_decode'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/encodings.rb:256:in `q_value_decode'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/encodings.rb:139:in `block (2 levels) in value_decode'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/encodings.rb:130:in `map'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/encodings.rb:130:in `block in value_decode'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/encodings.rb:122:in `map'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/encodings.rb:122:in `value_decode'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/encodings.rb:101:in `decode_encode'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/fields/unstructured_field.rb:73:in `do_decode'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/fields/unstructured_field.rb:55:in `decoded'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/fields/unstructured_field.rb:59:in `default'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/field.rb:165:in `method_missing'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/message.rb:1107:in `default'
    from /home/gaute/.rvm/gems/ruby-1.9.3-p392/gems/mail-2.5.3/lib/mail/message.rb:1042:in `subject'
    from (irb):4
    from /home/gaute/.rvm/rubies/ruby-1.9.3-p392/bin/irb:16:in `<main>'1.9.3-p392 :005 > m
```

same behavior on ruby 2.0.0.

Cheers, Gaute

**Comment by jeremy** [comment]
Check out #785 to provide your own charset encoder. BestEffortCharsetEncoder maps Windows-1258 to Windows-1252.

**Comment by jeremy** [comment]
Mail 2.7+ uses best effort encoder by default, so Windows-1258 charsets "just work."

**Comment by sk-** [comment]
Note that this seems to be partially fixed, as in some cases the result is incorrect.

For example:

```ruby
Mail::Encodings.decode_encode("=?windows-1258?Q?INVITACIO=ECN.pdf?=", :decode)
```

returns `"INVITACIOìN.pdf"` where it should have returned `"INVITACIÓN.pdf"`.

Try it out at http://dogmamix.com/MimeHeadersDecoder/
