### ISSUE TITLE
Date parser fails with invalid time: 30:00

### ISSUE THREAD

**Issue by gauteh** [mikel/mail#564]
The date parse fails if the Date field in the raw source is of the kind:

```
Date:   Wed, 7 Nov 2007 30:00:45 +0700
```

With the following error:

```
/home/gaute/dev/ruby/mail/lib/mail/parsers/ragel/ruby/machines/date_time_machine.rb:576:in `parse': undefined method `length' for nil:NilClass (NoMethodError)
    from /home/gaute/dev/ruby/mail/lib/mail/parsers/ragel/ruby.rb:24:in `parse'
    from /home/gaute/dev/ruby/mail/lib/mail/parsers/ragel.rb:9:in `parse'
    from /home/gaute/dev/ruby/mail/lib/mail/parsers/date_time_parser.rb:10:in `parse'
    from /home/gaute/dev/ruby/mail/lib/mail/elements/date_time_element.rb:8:in `initialize'
    from /home/gaute/dev/ruby/mail/lib/mail/fields/common/common_date.rb:34:in `new'
    from /home/gaute/dev/ruby/mail/lib/mail/fields/common/common_date.rb:34:in `element'
    from /home/gaute/dev/ruby/mail/lib/mail/fields/common/common_date.rb:6:in `date_time'
    from /home/gaute/dev/ruby/mail/lib/mail/fields/common/common_date.rb:10:in `default'
    from /home/gaute/dev/ruby/mail/lib/mail/field.rb:183:in `method_missing'
    from /home/gaute/dev/ruby/mail/lib/mail/message.rb:1187:in `default'
    from /home/gaute/dev/ruby/mail/lib/mail/message.rb:592:in `date'
    from testmail.rb:10:in `<main>'
```

Loading the mail using:

```
r = File.read 'mail'
m = Mail.read_from_source r
m.date
```

**Comment by jeremy** [comment]
#594
