### ISSUE TITLE
Redmine receive mail field

### ISSUE THREAD

**Issue by dmitrino** [mikel/mail#632]
I have redmine site:
```
Environment:
  Redmine version                2.3.3.devel
  Ruby version                   1.9.3-p448 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.7.1
```
I updated ruby and redmine, receiving mail not working (it worked before)
```
/usr/bin/rake -f /var/www/html/redmine/Rakefile --silent redmine:email:receive_pop3 RAILS_ENV="production" host=mail.my.site username=redmine@my.site password=mypassword delete_unprocessed=1 --trace
Your FCGI gem does not contain the FCGI shared library, running pure ruby instead
*\* Invoke redmine:email:receive_pop3 (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine:email:receive_pop3
rake aborted!
"\xCE" from ASCII-8BIT to UTF-8
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/fields/unstructured_field.rb:149:in `encode!'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/fields/unstructured_field.rb:149:in`fold'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/fields/unstructured_field.rb:103:in `wrapped_value'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/fields/unstructured_field.rb:69:in`do_encode'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/fields/unstructured_field.rb:51:in `encoded'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/field.rb:167:in`method_missing'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/header.rb:206:in `block in encoded'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/header.rb:205:in`each'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/header.rb:205:in `encoded'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/mail-2.5.4/lib/mail/message.rb:1801:in`encoded'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:434:in `set_payload_for_mail'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:403:in`block in receive'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `block in instrument'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `instrument'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:401:in`receive'
/var/www/html/redmine/app/models/mail_handler.rb:46:in `receive'
/var/www/html/redmine/lib/redmine/pop3.rb:39:in`block (2 levels) in check'
/usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/pop.rb:665:in `each'
/usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/pop.rb:665:in`each_mail'
/var/www/html/redmine/lib/redmine/pop3.rb:36:in `block in check'
/usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/pop.rb:533:in`start'
/var/www/html/redmine/lib/redmine/pop3.rb:31:in `check'
/var/www/html/redmine/lib/tasks/email.rake:152:in`block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/task.rb:236:in`block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/task.rb:231:in`execute'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/task.rb:161:in`invoke'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:106:in`block in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:100:in`top_level'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:165:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/rake-10.1.0/bin/rake:33:in`<top (required)>'
/usr/bin/rake:23:in `load'
/usr/bin/rake:23:in`<main>'
Tasks: TOP => redmine:email:receive_pop3
```
please help

**Comment by jeremy** [comment]
Double conversion error. Should work if you set the default external encoding or upgrade to Ruby 2.0+ where it's set to UTF-8 by default.
