### ISSUE TITLE
Net::ReadTimeout with 2.5.4, but not 2.5.3

### ISSUE THREAD

**Issue by ammar** [mikel/mail#639]
I'm consistently getting a Net::ReadTimeout exception with version 2.5.4. With the same exact configuration but using mail 2.5.3 everything works. I tested this by changing the version number in Gemfile.lock directly (there were two instances), and nothing else.

So, for now, with Rails 3.2.14 and Rails 4.0.1, I change the version number of mail to 2.5.3 in Gemfile.lock when I deploy and everything works fine.

The configuration used with both versions (in config/initializers/mailer.rb)

``` ruby
ActionMailer::Base.delivery_method = :smtp
ActionMailer::Base.smtp_settings = {
  :address                => "mail.domain.net",
  :port                   => "465",
  :domain                 => "domain.net",
  :authentication         => :plain,
  :enable_starttls_auto   => true,
  :openssl_verify_mode    => "none",
  :user_name              => "notifier@domain.net",
  :password               => "password"
}
```

The backtrace I get with 2.5.4

```
NOTIFICATION ERROR: Net::ReadTimeout
/usr/local/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill'
/usr/local/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
/usr/local/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
/usr/local/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
/usr/local/lib/ruby/2.0.0/net/smtp.rb:931:in `recv_response'
/usr/local/lib/ruby/2.0.0/net/smtp.rb:554:in `block in do_start'
/usr/local/lib/ruby/2.0.0/net/smtp.rb:941:in `critical'
/usr/local/lib/ruby/2.0.0/net/smtp.rb:554:in `do_start'
/usr/local/lib/ruby/2.0.0/net/smtp.rb:519:in `start'
/var/www/app/shared/bundle/ruby/2.0.0/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/var/www/app/shared/bundle/ruby/2.0.0/gems/mail-2.5.4/lib/mail/message.rb:248:in `deliver!'
/var/www/app/releases/20131121134619/app/models/notification.rb:25:in `block in daily_summary'
/var/www/app/releases/20131121134619/app/models/notification.rb:8:in `each'
/var/www/app/releases/20131121134619/app/models/notification.rb:8:in `daily_summary'
/var/www/app/releases/20131121134619/lib/tasks/notifications.rake:61:in `block (4 levels) in <top (required)>'
/var/www/app/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.1/lib/active_record/relation/delegation.rb:13:in `each'
/var/www/app/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.1/lib/active_record/relation/delegation.rb:13:in `each'
/var/www/app/releases/20131121134619/lib/tasks/notifications.rake:58:in `block (3 levels) in <top (required)>'
/var/www/app/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.1/lib/active_record/relation/delegation.rb:13:in `each'
/var/www/app/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.1/lib/active_record/relation/delegation.rb:13:in `each'
/var/www/app/releases/20131121134619/lib/tasks/notifications.rake:38:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

I'm happy to provide more information if needed, and to debug if someone has pointers.

Thanks!

**Comment by indiba** [comment]
When I try to send mail again and again " Net::ReadTimeout (Net::ReadTimeout) " this error comes . My present mail version is (~> 2.5, >= 2.5.4) , when I tried to change my mail version to  2.5.3 its throughing an load error . My rails version  is 4.2.4 and ruby version is 2.2.1 . Please help me if possible . Thanks
