### ISSUE TITLE
The ECONNREFUSED exception should be caught

### ISSUE THREAD

**Issue by bmurtagh** [mikel/mail#726]
I'm running into an issue attempting to send email. This SMTP server requires authentication which I'm supplying, but I'm getting an error:

```
/usr/local/lib/ruby/2.0.0/net/smtp.rb:541:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
```

Currently the Mail Gem is not catching this exception and it should to provide more details as to why the connection was refused to aid in debugging.

**Comment by Aditya-Chowdhry** [comment]
```Ruby
require 'mail'

mail = Mail.new do
  from     'user1@gmail.com'
  to       'user2@gmail.com'
  subject  'Here is the image you wanted'
  body     'Hey there!'
  #add_file :filename => 'somefile.png', :content => File.read('/somefile.png')
end

Mail.defaults do
  delivery_method :smtp, { :address    => "smtp.gmail.com",
                          :port       => 587,
                          :user_name  => 'user1@gmail.com',
                          :password   => ENV['PASSWORD'],
                          :authentication => :plain,
                          :enable_starttls_auto => true
                        }
end

mail.deliver!
```
Stacktrace:
```Ruby
 ruby send_emails.rb
/usr/lib/ruby/2.1.0/net/smtp.rb:541:in `initialize': Connection refused - connect(2) for "localhost" port 25 (Errno::ECONNREFUSED)
	from /usr/lib/ruby/2.1.0/net/smtp.rb:541:in `open'
	from /usr/lib/ruby/2.1.0/net/smtp.rb:541:in `tcp_socket'
	from /usr/lib/ruby/2.1.0/net/smtp.rb:551:in `block in do_start'
	from /usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.1.0/timeout.rb:101:in `call'
	from /usr/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
	from /usr/lib/ruby/2.1.0/net/smtp.rb:550:in `do_start'
	from /usr/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:252:in `deliver!'
	from send_emails.rb:21:in `<main>'
```

**Comment by Aditya-Chowdhry** [comment]
Okay got my mistake!
Mail.defaults should be the first thing to do.
