### ISSUE TITLE
names with [ / ] in them are not parseable

### ISSUE THREAD

**Issue by grosser** [mikel/mail#759]
```
::Mail::AddressList.new("[Group1] test <foo@bar.com>")
Mail::Field::ParseError: Mail::AddressList can not parse |[Group1] test <foo@bar.com>|
Reason was: Only able to parse up to [
    from /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mail-2.6.1/lib/mail/parsers/address_lists_parser.rb:14:in `parse'
    from /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mail-2.6.1/lib/mail/elements/address_list.rb:22:in `initialize'
    from (irb):2:in `new'
    from (irb):2
    from /opt/boxen/rbenv/versions/2.1.2/bin/irb:11:in `<main>'
```

fix:

``` Ruby
de_square(value) { |value| ::Mail::AddressList.new(value).addresses }

      def de_square(value)
        if value.include?("[") || value.include?("]")
          value = value.gsub("[", "SQUARE-OPEN-YEP").gsub("]", "SQUARE-CLOSE-YEP")
          addresses = yield value
          addresses.select(&:name).each do |address|
            address.name.gsub!("SQUARE-OPEN-YEP", "[")
            address.name.gsub!("SQUARE-CLOSE-YEP", "]")
          end
          addresses
        else
          yield value
        end
      end
```

/cc @jcheatham

**Comment by jeremy** [comment]
Only works when quoted. Can explore bending RFC to parse so long as it doesn't regress on legit address parsing.

**Comment by jcheatham** [comment]
woah... blast from the past :D
