### ISSUE TITLE
Empty content-disposition type blows up

### ISSUE THREAD

**Issue by grosser** [mikel/mail#794]
```
Content-Disposition:

fooo
```

->

```
NoMethodError: undefined method `each' for nil:NilClass
    /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/mail-8ab866ea2372/lib/mail/fields/content_disposition_field.rb:34:in `parameters'
    /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/mail-8ab866ea2372/lib/mail/fields/content_disposition_field.rb:61:in `decoded'
    /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/mail-8ab866ea2372/lib/mail/fields/structured_field.rb:43:in `default'
    /opt/boxen/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/mail-8ab866ea2372/lib/mail/field.rb:189:in `method_missing'
```

Fix:

``` Ruby
# https://github.com/mikel/mail/issues/794
Mail::ContentDispositionElement.class_eval do
  def parameters
    @parameters || []
  end
end
```

**Comment by jeremy** [comment]
```ruby
>> Mail.new(content_disposition: '').encoded
=> "Date: Tue, 16 May 2017 22:02:45 -0700\r\nMessage-ID: <591bd97577e3e_6f843ff91e433788108d@fork.local.mail>\r\nMime-Version: 1.0\r\nContent-Type: text/plain\r\nContent-Transfer-Encoding: 7bit\r\nContent-Disposition: \r\n\r\n"
```
