### ISSUE TITLE
Bad decoding of Form address

### ISSUE THREAD

**Issue by gimco** [mikel/mail#887]
We have found problems with the processing of some email addresses that includes chars using the charset ISO-8859-1. When the email is parsed, it's saved internally as ASCII-8BIT by default, and then is not possible encode to UTF-8. For example:

~~~ruby
require 'mail'

# An example mail input with iso8859-1 characters in the From field:
m = Mail.new "From: Jos\xE9 Garc\xEDa <jose@garcia.es>\r\n\r\nTest mail"

m[:from]
Encoding conversion failed "\xE9" from ASCII-8BIT to UTF-8
ArgumentError: invalid byte sequence in UTF-8
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `=~'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `!~'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/core_extensions/string.rb:26:in `blank?'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/fields/common/common_address.rb:117:in `block in do_decode'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/fields/common/common_address.rb:117:in `reject'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/fields/common/common_address.rb:117:in `do_decode'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/fields/from_field.rb:51:in `decoded'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/fields/common/common_field.rb:26:in `to_s'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/field.rb:162:in `inspect'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/field.rb:162:in `block in inspect'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/field.rb:161:in `map'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mail-2.6.3/lib/mail/field.rb:161:in `inspect'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/irb:12:in `<main>'

m[:from].encoded
 => "From: =?ASCII-8BIT?B?Sm9z6Q==?= =?ASCII-8BIT?B?IEdhcmPtYQ==?= <jose@garcia.es>\r\n" 
~~~

We're using `Ruby 1.9.3-p551` and `mail=2.6.3`

**Comment by gimco** [comment]
For the record, we've fixed temporarily monkey-patching the `initialize` method of the classes `Mail::StructuredField` and `Mail::UnstructuredField` to check if the value of the header is valid:

~~~ruby
begin
  self.value.encode('UTF-8') if self.value.respond_to?(:encode, :force_encoding)
rescue
  self.value = self.value.force_encoding('ISO-8859-1').encode('UTF-8')
end
~~~

**Comment by jeremy** [comment]
Confirm. We don't do charset detection, so if there's a mismatch, we can't automatically resolve it. It's up to you at this point.
