### ISSUE TITLE
Mail message drops recipient...

### ISSUE THREAD

**Issue by charlie-ablett** [mikel/mail#966]
Using Rails 3.2, Mail 2.4.4 on Ubuntu 10.04.4. I've got a mailer class in Rails 3.2 that refuses to send mail, giving the following error:

`Outgoing message to devs: #<Mail::Message:98270300, Multipart: false, Headers: <From: no-reply@example.com>, <To: dev@example.com>, <Subject: Error with script>, <Mime-Version: 1.0>, <Content-Type: text/html>>`

`rake aborted!`

`At least one recipient (To, Cc or Bcc) is required to send a message`

... yet the `to` field clearly has a recipient! It's completely boggling my mind.

Here's my mailer class:

    class Notifier < ActionMailer::Base
      def mail_current_developers(error)
        @error = error
        mail to: "dev@example.com", subject: "Error with script"
      end
    end

Here's my rake task:

    begin
      task :import_bars
        begin
          Foo.import_foos
        rescue => error
          mail = Notifier.mail_current_developers(error)
          puts "Outgoing message to devs: #{mail.inspect}"
          mail.deliver!
        end
      end
    end

This seems just so curly so I'm not sure what to do or why this error is occurring. Help?

Here's some additional info:

    => #<Mail::Message:82292730, Multipart: false, Headers: <From: no-reply@example.com>, <To: ["dev@example.com"]>, <Subject:  Error with script>, <Mime-Version: 1.0>, <Content-Type: text/html>> 
    system :002 > 
    system :003 >   mail.to
     => ["dev@example.com"] 
    system :004 > mail.deliver!
    ArgumentError: At least one recipient (To, Cc or Bcc) is required to send a message
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/mail-2.4.4/lib/mail/network/delivery_methods/smtp.rb:104:in `deliver!'
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/mail-2.4.4/lib/mail/message.rb:245:in `deliver!'
	from (irb):4
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/commands/console.rb:47:in `start'
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
    system :005 > mail.to = "dev@example.com"
     => "dev@example.com" 
    system :006 > mail.deliver!
    ArgumentError: At least one recipient (To, Cc or Bcc) is required to send a message
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/mail-2.4.4/lib/mail/network/delivery_methods/smtp.rb:104:in `deliver!'
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/mail-2.4.4/lib/mail/message.rb:245:in `deliver!'
	from (irb):6
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/commands/console.rb:47:in `start'
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
	from /home/example/staging/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

More digging in my shell, invoking some methods on Message:

    system :011 > mail.to ? [mail.to].flatten : [] # from message.rb in the Mail gem
     => [] 
    system :012 > mail.to
     => [] 
    system :013 > mail.inspect
     => "#<Mail::Message:82292730, Multipart: false, Headers: <From: no-reply@example.com>, <To: [\"\"]>, <Subject: Error with script>, <Mime-Version: 1.0>, <Content-Type: text/html>>" 
    
Why has the `to` field turned into `[\"\"]` ?? Some sort of encoding hiccup?

So I then do 

    system :014 > mail.to = "dev@example.com"
     => "dev@example.com" 
    system :015 > mail.destinations
     => ["dev@example.com"] 

Should be ok, right?

    system :018 > mail.deliver!
    ArgumentError: At least one recipient (To, Cc or Bcc) is required to send a message
    system :019 > mail
     => #<Mail::Message:82292730, Multipart: false, Headers: <From: no-reply@example.com>, <To: [""]>, <Subject: Error with script>, <Mime-Version: 1.0>, <Content-Type: text/html>>

Argh! Now `to` is `[""]`! 

This is a bit of a legacy system and I've just started getting this. The mail sent just yesterday, and doesn't seem to want to send at all. I haven't made any gem or OS changes. Any help or suggestions gratefully received!

**Comment by charlie-ablett** [comment]
Turns out they were being caught by MailSafe.
